# Generated by Django 5.2.6 on 2026-10-04 22:37

import core.fields
import datarooms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0006_dataroom_vault_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='banner_mode',
            field=models.CharField(choices=[('single', 'Single banner image'), ('gallery', 'Banner gallery'), ('none', 'No banner')], default='single', help_text='Which banner surface to render on the share page: single image, gallery, or none.', max_length=16),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='brand_logo_override',
            field=models.ImageField(blank=True, help_text='Optional per-dataroom logo; falls back to the organization logo when empty.', null=True, upload_to=datarooms.models.dataroom_branding_logo_path),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='enable_telemetry_access',
            field=models.BooleanField(default=False, help_text="Show the 'View telemetry' button in the share viewer for this dataroom."),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='logo_mode',
            field=models.CharField(choices=[('org', 'Organization logo (fallback)'), ('dataroom', 'Dataroom logo'), ('none', 'No logo')], default='org', help_text='Which logo surface to render: dataroom override, organization logo, or none.', max_length=16),
        ),
        migrations.CreateModel(
            name='DataroomBannerImage',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=datarooms.models.dataroom_gallery_image_path)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='datarooms.dataroom')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'unique_together': {('dataroom', 'position')},
            },
        ),
    ]
