# Generated by Django 5.2.6 on 2026-10-04 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datarooms', '0007_dataroom_banner_mode_dataroom_brand_logo_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kiln', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('co2e_factor_t_per_t', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('co2e_factor_source', models.CharField(blank=True, default='', max_length=255)),
                ('is_simulated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_dataset', to='datarooms.dataroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('kind', models.CharField(choices=[('started', 'Started'), ('stopped', 'Stopped'), ('out_of_range', 'Temperature out of range')], max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='telemetry.telemetrydataset')),
            ],
            options={
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['dataset', 'ts'], name='telemetry_event_ds_ts')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('running', models.BooleanField(default=False)),
                ('temp_drying', models.FloatField(blank=True, null=True)),
                ('temp_pyrolysis', models.FloatField(blank=True, null=True)),
                ('temp_finishing', models.FloatField(blank=True, null=True)),
                ('feed_kg', models.FloatField(default=0.0)),
                ('char_kg', models.FloatField(default=0.0)),
                ('syngas_nm3h', models.FloatField(blank=True, null=True)),
                ('drum_rpm', models.FloatField(blank=True, null=True)),
                ('quality', models.FloatField(default=1.0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly', to='telemetry.telemetrydataset')),
            ],
            options={
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['dataset', 'ts'], name='telemetry_hourly_ds_ts')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'ts'), name='telemetry_hourly_unique')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('operating_state', models.CharField(blank=True, default='', max_length=64)),
                ('feed_kg_rate', models.FloatField(blank=True, null=True)),
                ('char_kg_rate', models.FloatField(blank=True, null=True)),
                ('temp_pyrolysis', models.FloatField(blank=True, null=True)),
                ('temp_finishing', models.FloatField(blank=True, null=True)),
                ('syngas_nm3h', models.FloatField(blank=True, null=True)),
                ('drum_rpm', models.FloatField(blank=True, null=True)),
                ('reactor_pressure_mbar', models.FloatField(blank=True, null=True)),
                ('flue_gas_line_pressure_mbar', models.FloatField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('correction_reason', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.telemetrydataset')),
            ],
            options={
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['dataset', 'ts'], name='telemetry_reading_ds_ts')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'ts'), name='telemetry_reading_unique')],
            },
        ),
    ]
